#!/usr/bin/env bash
set -euo pipefail
set +u
source /opt/ros/humble/setup.bash
set -u
cd /home/jungjinwoo/Platooning_with_CMDP
PYTHON_BIN="${PYTHON_BIN:-python3.10}"
: "${PLATOON_MAP:=Town04}"
: "${PLATOON_SPECTATOR_FOLLOW:=1}"
: "${PLATOON_REALTIME_TICK:=1}"
: "${PLATOON_LEADER_THROTTLE:=1.0}"
: "${PLATOON_ACCEL_MAX_STEPS:=900}"
: "${PLATOON_BRAKE_TARGET_SPEED_MIN:=0.0}"
: "${PLATOON_BRAKE_TARGET_SPEED_MAX:=0.0}"
: "${PLATOON_LEADER_BRAKE_DECEL_MIN:=6.0}"
: "${PLATOON_LEADER_BRAKE_DECEL_MAX:=9.0}"
: "${PLATOON_STOP_HOLD_STEPS_MIN:=120}"
: "${PLATOON_STOP_HOLD_STEPS_MAX:=220}"
: "${PLATOON_INITIAL_DISTANCE_MIN:=6.5}"
: "${PLATOON_INITIAL_DISTANCE_MAX:=7.5}"
: "${PLATOON_INITIAL_SPEED_MIN:=0.0}"
: "${PLATOON_INITIAL_SPEED_MAX:=2.0}"
: "${PLATOON_FALLBACK_KP:=0.6}"
: "${PLATOON_FALLBACK_KD:=0.8}"
: "${PLATOON_FALLBACK_MAX_THROTTLE:=1.0}"
: "${PLATOON_FALLBACK_MAX_BRAKE:=1.0}"
: "${PLATOON_FALLBACK_HEADWAY_SCALE:=0.55}"
: "${PLATOON_RL_BLEND_ALPHA:=0.15}"
export PLATOON_MAP PLATOON_SPECTATOR_FOLLOW PLATOON_REALTIME_TICK PLATOON_LEADER_THROTTLE PLATOON_ACCEL_MAX_STEPS PLATOON_BRAKE_TARGET_SPEED_MIN PLATOON_BRAKE_TARGET_SPEED_MAX PLATOON_LEADER_BRAKE_DECEL_MIN PLATOON_LEADER_BRAKE_DECEL_MAX PLATOON_STOP_HOLD_STEPS_MIN PLATOON_STOP_HOLD_STEPS_MAX PLATOON_INITIAL_DISTANCE_MIN PLATOON_INITIAL_DISTANCE_MAX PLATOON_INITIAL_SPEED_MIN PLATOON_INITIAL_SPEED_MAX PLATOON_FALLBACK_KP PLATOON_FALLBACK_KD PLATOON_FALLBACK_MAX_THROTTLE PLATOON_FALLBACK_MAX_BRAKE PLATOON_FALLBACK_HEADWAY_SCALE PLATOON_RL_BLEND_ALPHA
"$PYTHON_BIN" carla_bridge.py
